[package]
name = "discord-interchannel-message-mover"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.25", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
